# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djstripe', '0029_customer_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('subscriber', 'account', 'livemode')]),
        ),
    ]
