# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0030_auto_20170428_1402'),
        ('djstripe', '0030_auto_20170421_0941'),
    ]

    operations = [
    ]
