# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0030_auto_20170323_0535'),
        ('djstripe', '0029_customer_account'),
    ]

    operations = [
    ]
